### ISSUE TITLE
Transparent background text is no longer transparent

### ISSUE THREAD

**Issue by srfoster** [jeapostrophe/mode-lambda#20]
On Windows and Linux, we're experiencing a regression after the most recent commit:   

https://github.com/jeapostrophe/mode-lambda/commit/a8c2a3a4eb03f26be630caa9ababfe3128a1dd59

Namely, backgrounds on rendered text are not transparent anymore.

![mode-lambda-text-bug](https://user-images.githubusercontent.com/764563/62313668-2e5bf680-b446-11e9-911e-e1a5f70af1db.png)

**Comment by aBlender** [comment]
I think the issue is the change on line 56 of [mode-lambda/text/static.rkt](https://github.com/jeapostrophe/mode-lambda/commit/a8c2a3a4eb03f26be630caa9ababfe3128a1dd59#diff-5f8489d770383188626397bfbf9af069), where `make-bitmap` is changed to `make-screen-bitmap`.

`make-screen-bitmap` uses `make-platform-bitmap` which doesn't have an alpha channel on Windows and Linux.

**Comment by jeapostrophe** [comment]
I believe you are correct @aBlender 

I changed it to get the backing scale correct Retina fonts on OS X. I think I may want to do `(make-object bitmap% w h #f #t (get-display-backing-scale))`. Can you check if that is good for you @srfoster ?

**Comment by aBlender** [comment]
Thank you @jeapostrophe for your quick response. Using `(make-object bitmap% width height #f #t (get-display-backing-scale))` does fix the alpha issue on our windows and linux machines.

**Comment by jeapostrophe** [comment]
Awesome, I just pushed that
